var synonyms = {
    "automotive": ["automobile", "car", "vehicle"],
    "car appraisers": ["auto appraisal", "car inspection", "auto inspection"],
    "car dealers and leasing": ["auto dealers", "auto leasing", "leasing service", "car sellers", "car dealership"],
    "used cars": ["used car dealer", "pre-owned car"],
    "car wash and detail": ["auto wash", "car detailing", "auto detail"],
    "classic and antique car": ["Old Antique automobiles", "classic automobiles", "classic cars"],
    "maintenance and repair": ["auto mechanics", "mechanics", "car mechanics", "car repair", "auto repair"],
    "oil and lube": ["oil change"],
    "smog check": ["smog test", "emission checks"],
    "tires": ["tyre", "car wheels"],
    "motorcycles, mopeds and scooters": ["bikes", "motor-bikes"],
    "repair": ["repairman", "mechanic"],
    "sales": ["dealer", "seller"],
    "rvs and motor homes": ["trailer homes"],
    "salvage yards": ["junkyards", "used auto parts"],
    "towing": ["tow truck", "towing service", "roadside", "roadside assistance"],
    "community and government": ["city government", "local government", "county government", "ministeries"],
    "animal shelters and humane societies": ["animal protection", "animal control", "animal pound"],
    "cemeteries": ["grave yards", "mortuaries", "memorial parks", "burial grounds"],
    "day care and preschools": ["pre-k schools", "nursery school", "day care center", "kindergarten", "child care"],
    "disabled persons services": ["disabled assistance", "handicap assistance"],
    "drug and alcohol services": ["substance abuse", "drug rehabs", "rehabilitation centers", "alcoholics anonymous", "narcotics anonymous"],
    "education": ["school", "learning", "teaching", "instruction", "training", "lessons"],
    "adult education": ["extension schools", "continuing education"],
    "art lessons and schools": ["art classes", "fine art schools", "photography schools", "design schools", "painting classes"],
    "colleges and universities": ["college campus", "higher education"],
    "computer training": ["computer classes", "tech school", "programming training"],
    "culinary lessons and schools": ["cooking schools", "cooking lessons", "cooking class"],
    "driving schools": ["driver's education", "driver's ed", "traffic school", "driving lessons", "driving instruction"],
    "fraternities and sororities": ["frats", "fraternal organizations", "sorority", "sorority house"],
    "primary and secondary schools": ["high schools", "junior high schools", "elementary schools", "middle schools", "grade school", "private schools", "public schools", "senior high school", "preparatory school"],
    "tutoring and educational services": ["study help", "prep courses", "test prep", "college prep", "test preparation", "preparation courses"],
    "vocational schools": ["technical schools", "trade schools"],
    "government departments and agencies": ["federal agencies", "government commissions", "government organizations"],
    "government lobbyists": ["activists", "special-interest groups", "PACs", "political action committees", "interest groups"],
    "housing assistance and shelters": ["homeless shelters", "crisis shelters", "women's shelter"],
    "law enforcement and public safety": ["public protection", "disaster prevention"],
    "rescue services": ["search and rescue", "SAR", "rescue squads"],
    "fire stations": ["fire department", "fire fighters"],
    "police stations": ["police departments", "PDs", "sheriff's office", "police office", "cops"],
    "libraries": ["public libraries"],
    "military": ["armed forces", "soldiers", "troops", "army", "navy", "air force"],
    "bases": ["center", "camp"],
    "organizations and associations": ["groups"],
    "charities and non-profits": ["volunteer organizations", "nonprofit", "NPO", "charity"],
    "environmental": ["ecological", "environment"],
    "youth organizations": ["child organizations", "child groups", "young people's groups", "young people's organizations"],
    "post offices": ["mail", "snail mail", "US post"],
    "public and social services": ["relief programs", "welfare", "support services", "public assistance"],
    "religious": ["places of worship", "house of prayer", "religion", "child welfare services"],
    "buddhist temples": ["monasteries", "pagoda", "stupa"],
    "churches": ["chapel"],
    "hindu temples": ["mandir", "devalayam", "murtis"],
    "mosques": ["masjid"],
    "synagogues": ["Jewish temple", "Samaritan temple"],
    "senior citizen services": ["elderly services", "senior centers", "meals-on-wheels"],
    "retirement": ["retire"],
    "healthcare": ["health care", "health management", "wellness program", "health maintenance", "medical", "medicine", "health"],
    "aids resources": ["AIDS testing centers", "AIDS services"],
    "assisted living services": ["assisted living facilities", "ALFs", "assisted living residencies"],
    "caretakers": ["attendants", "living assistants", "homecare"],
    "facilities and nursing homes": ["special care facility", "rest home", "convalescent hospital", "convalescent home"],
    "blood banks and centers": ["blood donor center", "bloodmobile"],
    "chiropractors": ["back doctors", "neuromusculoskeletal doctors"],
    "dentists": ["dental"],
    "emergency services": ["emergency response", "urgent response"],
    "ambulance": [],
    "holistic, alternative and naturopathic medicine": ["alternative and naturopathic medicine", "homeopathy"],
    "acupuncture": [],
    "hospitals, clinics and medical centers": [],
    "medical supplies and labs": ["clinical lab", "medical laboratories", "clinical research", "medical research"],
    "mental health": ["mental illness", "emotional health"],
    "counseling and therapy": ["grief counseling", "intervention", "marriage counseling", "social therapy"],
    "psychologists": ["psychology", "psychological counseling"],
    "nurses": ["registered nurses", "RNs", "nurse practitioner"],
    "pharmacies": ["drug store", "pharmaceuticals", "RX"],
    "physical therapy and rehabilitation": ["physiotherapy"],
    "sports medicine": ["physical fitness treatment"],
    "physicians": ["doctors", "MDs", "general practitioner"],
    "anesthesiologists": ["anaesthesia", "perioperative medicine"],
    "cardiologists": ["heart doctors", "cardiology"],
    "dermatologists": ["skin doctors", "dermatology"],
    "ear, nose and throat": ["Otolaryngologist", "ear doctor", "nose doctor", "throat doctor"],
    "family medicine": ["family doctor", "primary care", "family physician"],
    "gastroenterologists": ["digestive system doctors", "digestive system", "gastroenterology", "digestive disorder"],
    "general surgery": ["surgery"],
    "internal medicine": ["preventive medicine", "internist"],
    "neurologists": ["brain doctors", "neurology", "nervous sytem", "neurological disorders"],
    "obstetricians and gynecologists": ["obgyn", "gyno", " gynaecology"],
    "oncologists": ["cancer doctors", "oncology", "radiation treatment", "cancer treatment"],
    "ophthalmologists": ["eye surgeons", "eye doctors", "optometrist"],
    "orthopedic surgeons": ["musculoskeletal doctors", "orthopedic doctors", "orthopedists", "orthopedist"],
    "pathologists": ["disease doctors", "pathology"],
    "pediatricians": ["children's health", "infant health", "adolescent health"],
    "plastic surgeons": ["cosmetic surgeons", "cosmetic surgery", "aesthetic surgery", "aesthetic surgeon"],
    "psychiatrists": ["mental illness doctors", "mental disorders", "psychopharmacological "],
    "radiologists": ["x-ray technicians"],
    "respiratory": ["pulmonologist", "lung doctor"],
    "urologists": ["bladder doctor"],
    "podiatrists": ["feet doctor", "foot doctor"],
    "pregnancy and sexual health": ["reproductive health", "gyno", "OBGYN"],
    "weight loss and nutritionists": ["diet specialist", "nutrition counselor", "dietician", "nutritionist"],
    "landmarks": ["places to see", "points of interest"],
    "buildings and structures": ["famous buildings", "famous bridge", "skyscraper", "famous plaza", "famous church"],
    "gardens": ["botanical garden", "chinese garden", "community garden", "feng shui garden", "hanging garden"],
    "historic and protected sites": ["heritage site", "historical place", "historical site", "preserved sites"],
    "monuments and memorials": ["commemorations", "historic monument", "monumental sculpture"],
    "beaches": ["coasts", "shores", "waterfronts"],
    "mountains": ["mountain range", "alps", "peak", "mount", "mountain ridge", "volcano"],
    "forests": ["woods", "thickets"],
    "lakes": ["body of water"],
    "rivers": ["estuaries", "streams", "creek", "brook"],
    "parks": [],
    "natural parks": ["national park", "national forest", "preservesnature conservancy land", "national wildlife refuge"],
    "picnic areas": ["picnicking"],
    "playgrounds": ["jungle gyms", "playing field"],
    "urban parks": ["city parks", "county parks"],
    "retail": ["shopping", "stores", "buy"],
    "adult": ["strip clubs", "gentleman's clubs"],
    "antiques": ["antique dealers", "heirlooms", "old collectable"],
    "arts and crafts": ["art supplies", "craft store"],
    "auctions": ["auctioneer", "auction markets", "sale by bid"],
    "beauty products": ["beauty supplies", "beauty supply store", "personal care product", "skin care product", "cosmetics", "hair care product"],
    "bicycles": ["biking", "cycling", "bikes"],
    "bookstores": ["book dealers", "booksellers", "bookshop"],
    "cards and stationery": ["greeting cards", "invitations & announcements "],
    "children": ["kids clothing", "toddlers clothing", "children's clothing store", "children's products", "kids shoes"],
    "computers and electronics": ["electronics store", "computer hardware", "gadgets", "computer montior", "DVD player"],
    "cameras": ["digital cameras"],
    "mobile phones": ["cell phones"],
    "video games": ["electronic games", "game store"],
    "construction supplies": ["construction materials", "building materials", "construction hardware"],
    "convenience stores": ["mini-mart"],
    "costumes": ["Halloween costumes", "party costumes"],
    "dance and music": ["dance supplies", "musical instruments", "dance-wear", "ballet supplies", "music sheets"],
    "department stores": ["discount stores", "hypermarket"],
    "fashion": ["designers", "fashion collections", "haut couture"],
    "clothing and accessories": ["clothing stores", "clothing designer", "scarves", "gloves", "purse", "socks", "stockings"],
    "jewelry and watches": ["jewelers", "jewelry designer", "necklace", "earrings", "bracelet"],
    "shoes": ["footwear", "shoe sales", "boots", "sandals"],
    "swimwear": ["swimsuits", "bathing suits"],
    "flea markets": ["swap meet"],
    "florists": ["flower shops", "floral arrangements", "floral designs", "flowers"],
    "food and beverage": ["food services", "food suppliers", "beverage suppliers"],
    "beer, wine and spirits": ["wine", "spirits", "liquor", "liquor stores", "alcoholic beverages", "wine shop", "alcohol"],
    "candy stores": ["candies", "sweets"],
    "cheese": [],
    "chocolate": ["chocolatier"],
    "farmers' markets": ["farmers market"],
    "health and diet food": ["low fat food", "organic", "gluten-free"],
    "kosher": ["Jewish food"],
    "furniture and decor": ["home furnishings", "home decoration"],
    "gift and novelty": ["gift shop"],
    "glasses and optometrist": ["eye glasses", "eye exams"],
    "hobby and collectibles": [],
    "luggage": ["suitcases", "traveling baggage"],
    "music, video and dvd": ["video", "dvd", "music CD", "dvd rental", "video rental", "video store", "music shop"],
    "newsstands": ["newspapers", "magazines"],
    "nurseries and garden centers": ["plant nursery", "garden tools", "garden supplies", "gardening material", "gardening supplies"],
    "outlet": ["outlet store", "outlet shop"],
    "pawn shops": ["pawnbroker"],
    "pets": ["pet animals", "pet store", "pet grooming", "kennel", "pet supplies"],
    "photos and frames": ["frame store", "pictures"],
    "shopping centers and malls": ["shopping arcade", "shopping mall", "strip mall"],
    "sporting goods": ["athletic goods", "sports equipment"],
    "supermarkets and groceries": ["grocery store", "hypermarket"],
    "tobacco": ["cigar shops", "cigarette"],
    "toys": ["children's toys", "children's games"],
    "vintage and thrift": ["vintage store", "thrift store", "vintage shop"],
    "warehouses and wholesale stores": [],
    "wedding and bridal": ["bridal services", "wedding gowns", "bridal shops"],
    "businesses and services": ["business  ", "professionals"],
    "business and strategy consulting": ["business management consulting", "business planning "],
    "industrial machinery and vehicles": ["heavy equipment", "commercial machines"],
    "logging and sawmills": ["lumber production", "timber production", "raw wood suppliers"],
    "metals": ["metal supplies", "scrap steel seller", "stainless steel", "aluminum", "iron seller"],
    "packaging": ["crating & boxing", "packaging supplies"],
    "petroleum": ["crude oil", "fuel oil"],
    "plastics": ["plastic material", "plastic molding"],
    "refrigeration and ice": ["cooling equipment", "industrial freezers"],
    "rubber": ["rubber sheets", "rubber rolls", "industrial rubber"],
    "scientific": ["science-related services"],
    "security and safety": ["protection", "security alarm", "guards", "security camera"],
    "telecommunication services": ["phone systems", "telecoms"],
    "textiles": ["fabrics", "fabric shop", "fabric stores"],
    "water and waste management": ["sanitation services", "waste-water treatment"],
    "welding": ["welders", "metal workers"],
    "advertising and marketing": ["marketing programs", "advertising agents", "commercial strategies"],
    "advertising agencies and media buyers": ["commercial makers", "commercial art", "advertisements"],
    "creative services": ["graphic services", "photography", "design services"],
    "direct mail and email marketing services": ["PR services", "email campaign", "marketing automation"],
    "market research and consulting": ["market analysis", "sales consultant", "sales expert"],
    "online advertising": ["social media marketing", "Internet advertising", "web marketing", "online marketing"],
    "print, tv, radio and outdoor advertising": ["print ads", "tv advertising", "tv ads", "radio advertising", "radio ads", "outdoor advertising", "outdoor ads", "billboard ads", "newspaper advertising", "commercial broadcast"],
    "promotional items": ["promotional products", "promotional advertising"],
    "public relations": ["PR consultants", "public relations counselors", "industry relations"],
    "search engine marketing and optimization": ["paid search advertising", "pay per click marketing", "on-site and off-site optimization", "SEO"],
    "writing, copywriting and technical writing": ["copywriting", "technical writing", "commercial writings", "Technical communication", "Writing and editing services"],
    "agriculture and forestry": ["Lumbering", "Agricultural machinery", "Livestock", "Agricultural equipment"],
    "art restoration": ["Art repair", "Art conservation", "Painting restoration"],
    "audiovisual": ["Disc Jockeyes", "Audio and visual rentals", "Recording service"],
    "automation and control systems": ["Automated manufacturing", "automation services", "Home automation"],
    "chemicals and gasses": ["Combustibles", "Explosives", "Chemical compounds", "industrial chemical supplies", "industrial gasses"],
    "computers": ["Information technology services", "Computer networking devices", "software services", "IT solutions", "business computer support"],
    "corporate hq": ["Major corporations", "Center of operations", "Corporate administration"],
    "electrical equipment": ["Industrial Electronics", "industrial appliances"],
    "employment agencies": ["Recruiting services", "Employee leasing", "Staffing services"],
    "engineering": ["engineering structure and design", "Metamaterials", "Science engineering"],
    "entertainment": ["Theater production", "Video tape production", "Cinema industry", "musical services"],
    "media": ["Film production", "Television program production", "Animation", "radio production"],
    "equipment rental": ["Operated equipment rental", "Construction tool rental", "Professional tool rental"],
    "events and event planning": ["Event space", "Party planning", "Event scheduling", "event planner"],
    "atms": ["teller machines", "automated teller machines"],
    "financial": ["financial services", "Finance economics", "Capitalization", "financial institutes"],
    "accounting and bookkeeping": ["Auditing", "Financial reporting", "Tax accounting", "accountant", "bookeeper"],
    "banking and finance": ["Credit union", "Banks", "financial institutions"],
    "business brokers and franchises": ["intermediaries", "business valuations"],
    "check cashing": ["cash advance", "cashing services", "payday loans"],
    "collections": ["credit reporting and collection", "debt collection", "Financial recovery services", "accounts receivable"],
    "financial planning and investments": ["Investment advisers", "Investment broker", "Actuary", "financial advisers", "CFPs", "financial planner"],
    "fund raising": ["capital development", "revenue raising consulting services", "fund raising strategist", "fund raiser"],
    "loans and mortgages": ["lending institutions", "financing", "refinancing", "lenders"],
    "stock brokers": ["stock specialist", "retail brokers", "traders", "securities"],
    "student aid and grants": ["financial aid", "student loans", "educational lending"],
    "catering": ["caterer", "food preparation and delivery"],
    "distribution": ["distribution centers"],
    "funeral services": ["mortuary", "funeral home", "burial services", "morticians "],
    "geological": ["geological survey", "geological equipment", "geological services"],
    "home improvement": ["home remodeling", "home construction", "home building"],
    "architects": ["architectural design services", "building designs", "architectural services"],
    "carpenters": ["cabinet makers", "carpentry", "wood builder"],
    "carpet and flooring": ["floor material dealers", "flooring contractors", "carpet installations", "linoleum", "carpeting services", "flooring services"],
    "contractors": ["home builders", "construction workers"],
    "bathrooms": ["bath remodeling", "bathroom remodeling"],
    "deck and patio": ["porch construction", "deck builders", "patio builders"],
    "sewer": ["sewer builders", "sewer cleaners", "sewage services"],
    "doors and windows": ["window contractors", "window installers", "door manufacturers", "door installers"],
    "electricians": ["electrical contractors", "electrical services"],
    "fences, fireplaces and garage doors": ["fireplaces", "garage doors", "fence dealers", "garage door operating systems", "fireplaces and accessories", "fence installation", "fence installer"],
    "hardware and services": ["do-it-yourself stores", "hardware supplies"],
    "heating, ventilating and air conditioning": ["hvac", "ventilation contractors", "furnace services", "hvac", "air conditioning maintenance", "air conditioning repair"],
    "home appliances": ["household appliances", "home refrigerator", "dish washing machines", "washing machines", "home freezer", "clothes dryer", "kitchen stove", "miscowave", "tv set", "home cinema", "toaster oven", "fans"],
    "home inspection services": ["home surveyors", "home inspector"],
    "housewares": ["utensils", "serving dishes", "cooking dishes", "linnens", "baking dishes", "pots and pans", "silverware", "flatware", "bed sheets"],
    "interior design": ["decorating", "home design center", "interior designers", "interior decorator"],
    "kitchens": ["kitchen re-modelers", "kitchen builders", "kitchen cabinet makers"],
    "landscaping and gardeners": ["landscape designer", "landscape architect"],
    "lighting fixtures": ["lights", "lighting designs", "lamp stores"],
    "mobile homes": ["manufactured homes", "trailer homes", "trailers"],
    "movers": ["moving companies", "van and storage"],
    "painting": ["painters", "house painter"],
    "pest control": ["termite control", "exterminators"],
    "plumbing": ["plumbers", "plumbing system", "home water system"],
    "pools and spas": ["pool builders", "spa designers"],
    "roofers": ["roofing companies"],
    "storage": ["storage facilities", "secure storage", "self-storage"],
    "swimming pool maintenance and services": ["pool services", "pool cleaning", "pool care"],
    "tree service": ["gardener", "tree trimming", "tree care"],
    "upholstery": ["upholsterers", "reupholster"],
    "human resources": ["HR", "personnel", "human capital", "human resource management"],
    "import and export": ["exporters", "importers"],
    "leather": [],
    "legal": ["attorneys", "lawyers", "law services", "law firms", "barrister", "legal services", "legal representation"],
    "credit counseling and bankruptcy services": ["foreclosure services", "bankruptcy law", "financial counseling"],
    "immigration": ["naturalization consultants", "immigration lawyers"],
    "insurance": ["insurance agents", "insurance brokers", "risk management", "insurance agencies"],
    "machine shops": ["machining", "tool and dye"],
    "management": ["managers", "management services"],
    "manufacturing": ["fabrication", "production", "manufacturer"],
    "paper": ["paper product", "paper supplier"],
    "personal care": ["personal hygiene"],
    "dry cleaning, ironing and laundry": ["ironing", "laundry", "cleaners", "dry cleaners", "laundromat"],
    "hair removal": ["waxing services", "electrolysis"],
    "beauty salons and barbers": ["hair cutter", "hair stylists", "hair colorist", "hair styling", "blow dry", "hair highlights"],
    "manicures and pedicures": ["nail care", "nail treatment", "nail spa"],
    "massage clinics and therapists": ["physical therapists", "massage therapists", "masseuse"],
    "piercing": ["ear piercing", "nose piercing", "lip piercing", "tongue piercing", "body piercing"],
    "skin care": ["facials", "skin spas", "skin treatment"],
    "spas": ["spa resort", "day spa", "balneotherapy", "aromatherapy", "mud bath", "body wraps", "exfoliation", "microdermabrasion"],
    "tanning salons": ["tanning booth", "tanning bed"],
    "tattooing": ["body art", "tattoo parlor"],
    "printing, copying and signage": ["copying", "signage", "printers", "copy shop", "sign maker"],
    "professional cleaning": ["home cleaning", "janitorial services", "maid services"],
    "publishing": ["publishers", "publishing house"],
    "real estate": ["realty", "real property"],
    "property management": ["apartment managers", "building management"],
    "real estate agents": ["Realtors", "real estate brokers"],
    "real estate appraiser": ["building appraisor"],
    "real estate development and title companies": ["real estate developers", "title insurance"],
    "apartments, condos, and houses": ["condos", "houses", "residential real estate"],
    "boarding houses": ["rooming", "bed and board", "lodging house", "rooming house"],
    "building and land surveyors": ["building inspectors", "building surveyors"],
    "commercial real estate": ["commercial properties", "commercial building rental"],
    "corporate housing": ["corporate apartments", "corporate suites", "executive housing"],
    "renewable energy": ["solar energy", "green energy"],
    "repair services": ["repairman", "appliance repair"],
    "shipping, freight, and material transportation": ["freight", "material transportation", "industrial shipping", "car transportation"],
    "tailors": ["seamstress"],
    "veterinarians": ["animal doctor", "vet", "animal clinic"],
    "web design and development": ["website developmetn", "website maintenance"],
    "wholesale" : ["bulk sale"],
    "social": ["nightlife", "entertainment", "food and dining"],
    "art dealers and galleries": ["arts center", "art services", "art gallery"],
    "museums": ["art museum", "history museum", "science museum"],
    "bars": ["pub", "tavern", "cocktails", "drinks"],
    "hotel lounges": ["lounges", "hotel piano bar"],
    "jazz and blues cafes": ["jazz club", "blues club"],
    "sports bars": [],
    "wine bars": ["sommelier", "wine tasting", "tasting room"],
    "arcades and amusement parks": ["arcade games", "theme parks"],
    "billiard and pool": ["pool hall"],
    "bingo": ["bingo halls"],
    "bowling": ["bowling alley"],
    "carnivals": ["fun fair"],
    "casinos and gaming": ["gambling", "horse track", "race track"],
    "circuses": [],
    "dance halls and saloons": ["dancing"],
    "fairgrounds and rodeos": ["polo grounds"],
    "go carts": ["go karts", "go kart racing"],
    "hookah lounges": [],
    "karaoke": ["sing along"],
    "movie theatres": ["cinema", "movies"],
    "music and show venues": ["live performance", "concert halls", "playhouses"],
    "night clubs": ["dance clubs", "nightlife"],
    "party centers": [],
    "psychics and astrologers": ["mediums", "spiritual readings"],
    "ticket sales": ["box office", "will call"],
    "bagels and donuts": ["doughnut", "bagel shop"],
    "bakeries": ["pastries", "bakers"],
    "breweries": ["micro-brewer"],
    "cafes, coffee and tea houses": ["coffee", "tea houses", "coffee shops", "cafeterias"],
    "dessert": ["frozen desserts", "pie shops"],
    "ice cream parlors": ["frozen yogurt shops", "ice cream shop"],
    "internet cafes": [],
    "juice bars and smoothies": ["juice shop", "smoothie shop"],
    "restaurants": [],
    "american": [],
    "barbecue": ["BBQ", "ribs"],
    "buffets": ["all you can eat"],
    "burgers": ["hamburgers", "fries"],
    "chinese": ["Chinese noodles", "shou  mian", "bok choy", "moon cake", "chow mein", "kung pao"],
    "delis": ["delicatessen", "head cheese", "cold cuts"],
    "diners": [],
    "french": ["escargot", "foie gras", "bouillabaisse", "ratatouille", "ragout"],
    "indian": ["curry", "tandoori", "tikka masala", "palak paneer", "daal"],
    "italian": ["bruschetta", "insalata", "verdure", "carbonara", "risotto", "all'arrabbiata"],
    "japanese": ["sushi", "tempura", "sashimi", "sake", "nigiri", "teriyaki", "shabu-shabu", "ramen", "miso"],
    "korean": ["dakjuk", "yangnyeom tongdak", "kimchi", "bibimbap", "buldak"],
    "mexican": ["carne asada", "taco", "chorizo", "borrito", "tamale", "quesadilla", "pibil", "tortilla"],
    "middle eastern": ["hummus", "falafel", "tabouleh"],
    "pizza": ["thin crust", "domino's", "thick crust"],
    "seafood": ["crab legs", "grilled fish", "fried fish", "fresh lobster", "red lobster"],
    "steakhouses": ["steak", "petite filet", "filet mignon", "ribeye", "porthouse steak"],
    "sushi": ["(this should  merge with Japanese)"],
    "thai": ["phat thai", "khao man gai", "sweet and sour soup", "coconut soup", "tom yam kung", "spring rolls"],
    "vegan and vegetarian": ["raw food", "vegetarian restaurant"],
    "social clubs": ["country club", "sports club"],
    "wineries and vineyards": ["winery"],
    "zoos, aquariums and wildlife sanctuaries": ["aquariums", "wildlife sanctuaries", "wildlife parks"],
    "sports and recreation": ["athletics"],
    "athletic fields": ["playing fields"],
    "baseball": [],
    "batting ranges": [],
    "basketball": [],
    "combat sports": ["fighting sports"],
    "cycling": ["bicycling"],
    "dance": [],
    "equestrian": ["horseback riding", "riding", "horse riding"],
    "football": [],
    "golf": [],
    "gun ranges": ["shooting range"],
    "gymnastics": ["aerobatics", "tumbling"],
    "gyms and fitness centers": ["athletic clubs", "health clubs", "exercise room"],
    "hockey": ["ice hockey", "field hockey"],
    "outdoors": ["outdoor recreation", "adventure racing", "caving", "mushing"],
    "campgrounds and rv parks": ["camping", "backpacking"],
    "hiking": ["walking"],
    "hot air balloons": ["ballooning"],
    "hunting and fishing": [],
    "rock climbing": ["bouldering", "scaling", "climbing", "mountaineering"],
    "skydiving": ["parachuting"],
    "paintball": [],
    "personal trainers": ["fitness coach"],
    "race tracks": ["race courses"],
    "racquet sports": [],
    "racquetball": [],
    "tennis": [],
    "recreation centers": [],
    "running": ["jogging"],
    "skating": ["speed skating", "figure skating", "inline skating", "roller skating", "ice skating"],
    "snow sports": ["ski", "winter sport", "sledding", "snowboarding", "snowmobiling", "curling"],
    "soccer": [],
    "stadiums and arenas": ["amphitheater", "bowl", "sport stadium"],
    "swimming pools": ["public pools"],
    "water sports sportswater polo": ["surfing", "body boarding", "jet skiing", "kite surfing", "sailing", "water skiing", "wind surfing"],
    "boating": ["motor boating", "yatching"],
    "canoes and kayaks": ["canoeing", "kayaking", "rowing", "whitewater canoeing"],
    "rafting": ["white water rafting"],
    "scuba diving": ["snorkeling"],
    "swimming": ["open water swimming", "pool swimming", "diving", "synchronized swimming"],
    "yoga and pilates": [],
    "transportation": ["transit"],
    "airlines and aviation services": ["air service", "air shuttle"],
    "gas stations": ["gasoline station", "petrol station", "filling station"],
    "parking": [],
    "public transportation services": ["public transit"],
    "taxi and car services": ["taxi rental", "taxi cab", "yellow cab"],
    "car and truck rentals": ["auto rentals", "truck rental"],
    "charter buses": ["bus rentals"],
    "limos and chauffeurs": ["limo service", "limousines"],
    "transport hubs": ["transit centers", "intermodal transit stations", "stations", "transit stops"],
    "airports": ["airport terminals"],
    "bus stations": ["bus stops", "bus terminals"],
    "heliports": [],
    "ports": ["sea ports", "ferry ports", "ferry terminals"],
    "rail stations": ["railroad station", "rail terminal", "train station", "railroad terminal"],
    "travel": ["expedition", "tour", "excursion", "vacation", "trips"],
    "cruises": ["voyages", "liner", "luxury liner", "ocean liner"],
    "lodging": ["inn", "boarding house", "room", "room and board"],
    "bed and breakfasts": ["B&Bs", "B and Bs", "country inn", "guest house"],
    "cottages and cabins": ["log cabin", "cabin rentals", "lodge rentals"],
    "hostels": ["youth hostel", "youth hotel"],
    "hotels and motels": ["inns"],
    "lodges and vacation rentals": ["time shares", "retreats", "country houses"],
    "resorts": ["spa resort", "ski resort", "seaside resort", "getaway"],
    "tourist information and services": ["tourist centers", "information centers", "visitor centers", "visitors information"],
    "travel agents and tour operators": ["tour guides", "guided tours", "walking tours", "sightseeing", "travel guide", "travel planning", "getaway planning"],
    "car parts and accessories": [],
    "transmissions": [],
    "utility companies": [],
    "natural": [],
    "arts": [],
    "food and dining": [],
    "fast food": [],
    "sports clubs": [],
    "water sports": [],
    "geriatrics": [],
    "discount stores": [],
    "meat and seafood": [],
    "office supplies": [],
    "party supplies": [],
    "career counseling": [],
    "construction": [],
    "notary": [],
    "photography": [],
    "translation services": [],
    "golf courses": [],
    "surfing": [],
    "embassies": [],
    "infrastructure": [],
    "mobile": [],
    "advertising": [],
    "asian": [],
    "food trucks": [],
    "rest areas": [],
    "technology": []
}